# Generated by Django 3.0.2 on 2020-01-19 00:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import where2med_auth.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('address', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=10)),
                ('image', models.ImageField(height_field='image_heigth', upload_to=where2med_auth.models.get_image_file_path, width_field='image_width')),
                ('image_heigth', models.IntegerField(default=0, editable=False)),
                ('image_width', models.IntegerField(default=0, editable=False)),
                ('cost_per_consult', models.DecimalField(decimal_places=2, max_digits=8)),
                ('rating', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('phone', models.CharField(max_length=254)),
                ('city', models.CharField(max_length=254)),
                ('image', models.ImageField(height_field='image_heigth', upload_to=where2med_auth.models.get_image_file_path, width_field='image_width')),
                ('image_heigth', models.IntegerField(default=0, editable=False)),
                ('image_width', models.IntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='TelephoneAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('medical_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='where2med_auth.MedicalCenter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='where2med_auth.Patient')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='where2med_auth.Status')),
            ],
        ),
        migrations.CreateModel(
            name='PhysicalAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('medical_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='where2med_auth.MedicalCenter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='where2med_auth.Patient')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='where2med_auth.Status')),
            ],
        ),
        migrations.CreateModel(
            name='MedicalNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField(max_length=1024)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('medical_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='where2med_auth.MedicalCenter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='where2med_auth.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('address', models.CharField(max_length=254)),
                ('image', models.ImageField(height_field='image_heigth', upload_to=where2med_auth.models.get_image_file_path, width_field='image_width')),
                ('image_heigth', models.IntegerField(default=0, editable=False)),
                ('image_width', models.IntegerField(default=0, editable=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('medical_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='where2med_auth.MedicalCenter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('medical_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='where2med_auth.MedicalCenter')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='where2med_auth.Patient')),
            ],
            options={
                'unique_together': {('patient', 'medical_center')},
            },
        ),
        migrations.CreateModel(
            name='MedicalCenterService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medical_center', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='where2med_auth.MedicalCenter')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='where2med_auth.Service')),
            ],
            options={
                'unique_together': {('medical_center', 'service')},
            },
        ),
    ]
