# Generated by Django 3.0.2 on 2020-01-19 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('where2med_auth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalcenter',
            name='image',
        ),
        migrations.RemoveField(
            model_name='medicalcenter',
            name='image_heigth',
        ),
        migrations.RemoveField(
            model_name='medicalcenter',
            name='image_width',
        ),
    ]
