# Generated by Django 3.0.2 on 2020-01-19 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('where2med_auth', '0002_auto_20200119_0237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='image',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='image_heigth',
        ),
        migrations.RemoveField(
            model_name='admin',
            name='image_width',
        ),
    ]
