# Generated by Django 3.0.2 on 2020-01-19 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('where2med_auth', '0003_auto_20200119_0245'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='image',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='image_heigth',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='image_width',
        ),
    ]
